// Mocks generated by Mockito 5.4.5 from annotations
// in my_guia_de_moteis/test/repository/motel_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:my_guia_de_moteis/client/request_http_client.dart' as _i2;
import 'package:my_guia_de_moteis/repository/motel_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRequestHttpClient_0 extends _i1.SmartFake
    implements _i2.RequestHttpClient {
  _FakeRequestHttpClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RequestHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestHttpClient extends _i1.Mock implements _i2.RequestHttpClient {
  MockRequestHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> get(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [MotelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotelRepository extends _i1.Mock implements _i5.MotelRepository {
  MockMotelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RequestHttpClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeRequestHttpClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.RequestHttpClient);

  @override
  _i4.Future<Map<String, dynamic>> fetchMotelData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMotelData, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
